name: Deploy to WordPress.org
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        uses: shivammathur/setup-php@master
        with:
          php-version: '7.4'
          extensions: intl, mbstring, json, bcmath
          coverage: xdebug
          tools: composer:v1

      # Build the plugin with dev dependencies to scope the dependency packages.
      - name: Composer Install (Dev)
        run: composer install

      - name: Build
        run: |
          composer install --no-dev
          npm install
          gulp js:build
          gulp css:build

      # Install SVN ( Subversion )
      - name: Install SVN ( Subversion )
        run: |
          sudo apt-get update
          sudo apt-get install subversion

      # Deploy the plugin to WordPress.org
      - name: WordPress Plugin Deploy
        id: deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          generate-zip: true
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: swedbank-pay-payment-menu

       # Add release assets to the Github release tag.
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.deploy.outputs.zip-path }}
          asset_name: ${{ github.event.repository.name }}.zip
          asset_content_type: application/zip 