name: Deploy to WordPress.org
on:
  release:
      types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      # Build the plugin with dev dependencies to scope the dependency packages.
      - name: Composer Install (Dev)
        run: composer install

      - name: Build
        run: |
          composer install --no-dev
          npm ci
          gulp js:build
          gulp css:build

      # Install SVN ( Subversion )
      - name: Install SVN ( Subversion )
        run: |
          sudo apt-get update
          sudo apt-get install subversion

      # Deploy the plugin to WordPress.org
      - name: WordPress Plugin Deploy
        id: deploy
        uses: 10up/action-wordpress-plugin-deploy@54bd289b8525fd23a5c365ec369185f2966529c2 # 2.3.0
        with:
          generate-zip: true
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: swedbank-pay-payment-menu

       # Add release assets to the Github release tag.
      - name: Upload release asset
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.deploy.outputs.zip-path }}
          asset_name: ${{ github.event.repository.name }}.zip
          asset_content_type: application/zip
